# Generated by Django 4.2.13 on 2024-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='date_added',
        ),
        migrations.AddField(
            model_name='topic',
            name='text2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
