# Generated by Django 4.2.13 on 2024-06-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='text2',
        ),
    ]
