# Generated by Django 4.2.13 on 2024-07-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entry',
        ),
    ]
